version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tfg
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/tfg.sql:/docker-entrypoint-initdb.d/tfg.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
  
  backend:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db-data:
